name: Scrape NHK Easy News and Deploy to GitHub Pages

on:
  # Run daily at 9 AM JST (midnight UTC)
  schedule:
    - cron: "0 0 * * *"

  # Allow manual triggering
  workflow_dispatch:

  # Run on pushes to main branch for testing
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  scrape-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      - name: Create virtual environment and install dependencies
        run: |
          uv sync

      - name: Create data directory
        run: mkdir -p data

      - name: Cache WaniKani data
        uses: actions/cache@v3
        with:
          path: data/cache
          key: wanikani-cache-${{ hashFiles('src/wanikani.py') }}
          restore-keys: |
            wanikani-cache-

      - name: Run scraper and site generator
        env:
          WANIKANI_API_TOKEN: ${{ secrets.WANIKANI_API_TOKEN }}
        run: |
          cd src
          uv run python main.py

      - name: Upload artifacts for debugging
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: scraper-data
          path: |
            data/articles.json
            data/learned_kanji.json
          retention-days: 7

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: scrape-and-build

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
